import = [
  # "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/gruvbox-material-medium-dark.toml",
  # "~/.config/alacritty/rose-pine.toml",
  # "~/.config/alacritty/everforest-dark.toml",
  # "~/.config/alacritty/kanagawa-dragon.toml",
  # "~/.config/alacritty/black-metal-gorgoroth.toml",
  # "~/.config/alacritty/black-metal-venom.toml",
  "~/.config/alacritty/black-metal-gorgoroth-256.toml",
]

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[cursor]
unfocused_hollow = true

[font]
size = 16

[font.bold]
family = "0xProto Nerd Font"
# family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
# family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
# family = "FiraCode Nerd Font Mono"
# family = "Hack Nerd Font"
# family = "Iosevka Nerd Font"
# family = "3270 Nerd Font Mono"
# family = "CommitMono Nerd Font"
# family = "Monaspace Neon"
# family = "Monaspace Argon"
# family = "JetBrainsMonoNL Nerd Font"
# family = "MonaspiceNe Nerd Font Mono"
# family = "ZedMono Nerd Font Mono"
# family = "MesloLGL Nerd Font"
family = "0xProto Nerd Font"
style = "regular"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[window]
# startup_mode = "Fullscreen"
opacity = 0.80
blur = true
