format = "$os $username@$hostname $shell $sudo\n[┣❯](bold red) $directory\n[╰──❯ ](bold green)\n"
right_format = "$all\n"
[directory]
disabled = false
format = "[$path](bold cyan)[/](bold green)[$read_only](bold #FF0000) "
home_symbol = " "
read_only = "  "
truncate_to_repo = true
truncation_length = 12
truncation_symbol = "…/"
use_os_path_sep = true

[git_branch]
always_show_remote = true
disabled = false
format = "on [$symbol$branch(:$remote_branch)]($style) "
ignore_branches = []
only_attached = false
style = "bold blue"
symbol = " "
truncation_symbol = "..."

[git_commit]
commit_hash_length = 8
disabled = false
format = "[\\($hash$tag\\)]($style) "
only_detached = true
style = "bold green"
tag_disabled = false
tag_symbol = "笠"

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
disabled = false
format = "[+$added]($added_style)/[-$deleted]($deleted_style) "
only_nonzero_diffs = true

[git_state]
am = " AM"
am_or_rebase = " AM/REBASE"
bisect = " BISECTING"
cherry_pick = " CHERRY-PICKING"
disabled = false
format = "[($state( $progress_current of $progress_total))]($style) "
merge = " MERGING"
rebase = " REBASING"
revert = " REVERTING"
style = "bold red"

[git_status]
ahead = "[ $count](bold purple) "
behind = "[ $count](bold purple) "
conflicted = "= "
deleted = "[ $count](bold red) "
disabled = false
diverged = "󰧈 "
format = "([$all_status$ahead_behind]($style))"
ignore_submodules = false
modified = "[ $count](bold blue) "
renamed = "凜 "
staged = "[ $count](bold green) "
stashed = "[ ](cyan) "
style = "bold cyan"
untracked = "? "
up_to_date = " 󰥔 "

[hostname]
disabled = false
format = "[$hostname]($style)"
ssh_only = false
style = "bold dimmed green"

[os]
disabled = false
format = "[$symbol](bold blue)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = ""
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
openSUSE = " "

[shell]
bash_indicator = ""
cmd_indicator = ""
disabled = false
elvish_indicator = "elvish _"
fish_indicator = "🐟"
ion_indicator = "ino _"
nu_indicator = "nu _"
powershell_indicator = "_"
style = "bold green"
tcsh_indicator = "tcsh _"
unknown_indicator = ""
xonsh_indicator = "xonsh _"
zsh_indicator = "zsh"

[username]
disabled = false
format = "[$user]($style)"
show_always = true
