#!/bin/env bash

# Get the current keyboard layout
CURRENT_LAYOUT=$(setxkbmap -query | grep layout | awk '{print $2}')

# Toggle between US and Portuguese Latin
if [ "$CURRENT_LAYOUT" = "us" ]; then
    setxkbmap pt
else
    setxkbmap us
fi
