# Application bindings
$terminal = ghostty
$browser = firefox
$fileManager = nemo
$webapp = $browser -new-tab
$passwordManager = bitwarden

bind = SUPER, return, exec, $terminal
bind = SUPER, N, exec, $fileManager
bind = SUPER, B, exec, $browser

# bind = SUPER, A, exec, $webapp="https://chatgpt.com"
# bind = SUPER SHIFT, A, exec, $webapp="https://grok.com"
# bind = SUPER, C, exec, $webapp="https://app.hey.com/calendar/weeks/"
# bind = SUPER, E, exec, $webapp="https://app.hey.com"
# bind = SUPER, Y, exec, $webapp="https://youtube.com/"
# bind = SUPER SHIFT, G, exec, $webapp="https://web.whatsapp.com/"
# bind = SUPER ALT, G, exec, $webapp="https://messages.google.com/web/conversations"
# bind = SUPER, X, exec, $webapp="https://x.com/"
# bind = SUPER SHIFT, X, exec, $webapp="https://x.com/compose/post"
