# Launching
bind = SUPER, D, exec, rofi -show combi -modes combi -icon-theme "Papirus" -show-icons
bind = SUPER, C, exec, rofi -show calc -modi calc -no-show-match -no-sort 

# Notifications
bind = SUPER, comma, exec, makoctl dismiss bind = SUPER SHIFT, comma, exec, makoctl dismiss --all
bind = SUPER CTRL, comma, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

# Power menu controls lock, suspend, relaunch, restart, shutdown
bind = SUPER SHIFT, Q, exec, ~/.config/hypr/scripts/power-menu

# Toggle idling
bind = SUPER SHIFT, L, exec, hyprlock

# Screenshots
bind = , PRINT, exec, hyprshot -m region
bind = SUPER SHIFT, P, exec, hyprshot -m region

# Color picker
bind = SUPER, PRINT, exec, hyprpicker -a
