# source = ~/.config/hypr/themes/hyprland.conf

source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/envs.conf
source = ~/.config/hypr/conf/looknfeel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/windows.conf
source = ~/.config/hypr/conf/bindings/media.conf
source = ~/.config/hypr/conf/bindings/tiling.conf
source = ~/.config/hypr/conf/bindings/utilities.conf
source = ~/.config/hypr/conf/bindings/apps.conf
