# vim: ft=tmux

# Status bar styling
set -g status-position bottom
# bg=sumiInk1, fg=oldWhite
set -g status-style "bg=#1F1F28,fg=#C8C093"

# Window status
# Active: fg=sumiInk1, bg=springGreen
setw -g window-status-current-format "#[fg=#1F1F28,bg=#98BB6C]#[fg=#1F1F28,bg=#98BB6C,bold] #I #W #[fg=#98BB6C,bg=#1F1F28,nobold]"
# Inactive: fg=oldWhite, bg=sumiInk1
setw -g window-status-format "#[fg=#C8C093,bg=#1F1F28] #I #W "

# Left status
# Session Name: fg=oldWhite, bg=sumiInk3
set -g status-left "#[fg=#C8C093,bg=#363646,bold] #S #[fg=#363646,bg=#1F1F28,nobold] "
set -g status-left-length 50

set -g window-status-separator "  "

# Right status
# Transition blocks mimicking powerline logic (Dark -> Light Dark)
set -g status-right "#[fg=#363646,bg=#1F1F28]#[fg=#C8C093,bg=#363646] %H:%M #[fg=#363646,bg=#363646]#[fg=#C8C093,bg=#363646] %d-%b-%y "
set -g status-right-length 50
