# Status bar styling
set -g status-position bottom
set -g status-style "bg=#2b3339,fg=#d3c6aa"

# Window status
setw -g window-status-current-format "#[fg=#2b3339,bg=#a7c080]#[fg=#2b3339,bg=#a7c080,bold] #I #W #[fg=#a7c080,bg=#2b3339,nobold]"
setw -g window-status-format "#[fg=#d3c6aa,bg=#2b3339] #I #W "

# Left status
set -g status-left "#[fg=#d3c6aa,bg=#4b565c,bold] #S #[fg=#4b565c,bg=#2b3339,nobold] "
set -g status-left-length 20

set -g window-status-separator "  "

# Right status
set -g status-right "#[fg=#4b565c,bg=#2b3339]#[fg=#d3c6aa,bg=#4b565c] %H:%M #[fg=#4b565c,bg=#4b565c]#[fg=#d3c6aa,bg=#4b565c] %d-%b-%y "
set -g status-right-length 50
