#!/usr/bin/env bash

if [ x"$@" = x"ES" ]
then
    xdg-open https://fenix.tecnico.ulisboa.pt/disciplinas/QS11/2024-2025/1-semestre
    exit 0
elif [ x"$@" = x"ALC" ]
then
    xdg-open https://fenix.tecnico.ulisboa.pt/disciplinas/ALC11/2024-2025/1-semestre
    exit 0
elif [ x"$@" = x"CCEIC-I" ]
then
    xdg-open https://fenix.tecnico.ulisboa.pt/disciplinas/CCEIC11/2024-2025/1-semestre
    exit 0
elif [ x"$@" = x"ES-Project" ]
then
    xdg-open https://github.com/joserlopes/Software-Specification
    exit 0
elif [ x"$@" = x"ALC-Project" ]
then
    xdg-open https://github.com/joserlopes/Algorithms-for-Computational-Logic
    exit 0
elif [ x"$@" = x"GitHub" ]
then
    xdg-open https://github.com/joserlopes
    exit 0
elif [ x"$@" = x"dotfiles" ]
then
    xdg-open https://github.com/joserlopes/dotfiles
    exit 0
fi
echo "ES"
echo "ALC"
echo "CCEIC-I"
echo "ES-Project"
echo "ALC-Project"
echo "GitHub"
echo "dotfiles"
