#!/usr/bin/env bash

if [ x"$@" = x"AS" ]
then
    xdg-open https://fenix.tecnico.ulisboa.pt/disciplinas/ASof11/2024-2025/1-semestre
    exit 0
elif [ x"$@" = x"SSof" ]
then
    xdg-open https://fenix.tecnico.ulisboa.pt/disciplinas/SSof11/2024-2025/1-semestre
    exit 0
elif [ x"$@" = x"SSof-GitLab" ]
then
    xdg-open https://gitlab.rnl.tecnico.ulisboa.pt/ssof2425
    exit 0
elif [ x"$@" = x"Quizzes Tutor" ]
then
    xdg-open https://quizzes-tutor.tecnico.ulisboa.pt/
    exit 0
elif [ x"$@" = x"GitHub" ]
then
    xdg-open https://github.com/joserlopes
    exit 0
elif [ x"$@" = x"dotfiles" ]
then
    xdg-open https://github.com/joserlopes/dotfiles
    exit 0
fi
echo "AS"
echo "SSof"
echo "SSof-GitLab"
echo "Quizzes Tutor"
echo "GitHub"
echo "dotfiles"
