exec-once = mako & waybar
exec-once = wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'
exec-once = dropbox-cli start
exec-once = nm-applet
exec-once = swaybg -i ~/dotfiles/wallpapers/Paysage.png -m fill
exec-once = ~/.config/hypr/scripts/notify-track-change
