import = [
 # "~/.config/alacritty/catppuccin-frappe.toml"
 # "~/.config/alacritty/gruvbox-material-medium-dark.toml"
  "~/.config/alacritty/everforest-dark.toml"
]

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[cursor]
unfocused_hollow = true

[font]
size = 16

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
# family = "JetBrains Mono"
# family = "FiraCode Nerd Font Mono"
# family = "Hack Nerd Font"
# family = "Iosevka Nerd Font"
# family = "3270 Nerd Font Mono"
# family = "CommitMono Nerd Font"
# family = "Monaspace Neon"
# family = "Monaspace Argon"
family = "0xProto"
style = "regular"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[window]
# startup_mode = "FullScreen"
opacity = 0.80
blur = true
