[[block]]
block = "focused_window"

[block.format]
full = " $title.str(max_w:20) |"
short = " $title.str(max_w:10) |"

[[block]]
alert = 10.0
alert_unit = "GB"
block = "disk_space"
format = " $icon root: $available.eng(w:2) "
info_type = "available"
interval = 20
path = "~/"
warning = 20.0

[[block.click]]
button = "left"
cmd = "nemo"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20, rot_interval:0.5) $prev $play $next |} "
format_alt = " $icon "
seek_step_secs = 10

[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
device_kind = "source"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %d/%m/%Y %H:%M:%S') "
interval = 5

[[block]]
block = "bluetooth"
disconnected_format = ""
format = " $icon $name $percentage "
mac = "74:45:CE:10:A7:1A"

[[block.click]]
button = "left"
cmd = "blueman-manager"

[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "bluetooth"
disconnected_format = ""
format = " $icon $name "
mac = "28:06:DE:00:05:8A"

[[block.click]]
button = "left"
cmd = "blueman-manager"

[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"

[[block]]
block = "backlight"
format = " $icon $brightness"
missing_format = ""

[[block]]
block = "hueshift"
click_temp = 3500
format = " $temperature "
hue_shifter = "redshift"
interval = 60
step = 50

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid |Wired connection}"

[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[icons]
icons = "material-nf"

[theme]
theme = "gruvbox-dark"
